QuiltMC/developer-wiki

- buildSrc/src/main/java/quilt/internal/GenerateWikiTask.java
- buildSrc/src/main/java/quilt/internal/GenerateWikiTreeTask.java
- buildSrc/src/main/java/quilt/internal/WikiStructure.java
- wiki/templates/master_template.html
This PR add meta tags to pages to improve SEO & improve the preview embed (for example on discord).
Close #11.
> Add meta tags to pages

- buildSrc/src/main/java/quilt/internal/GenerateWikiTask.java
- wiki/templates/404.html
This PR add 404 page like https://quiltmc.org.
Example link : https://mysterious-dev.github.io/Test-Github/test-quilt
> Add 404 page

- wiki/templates/master_template.html
This PR fix missing doctype on the top of pages
> Fix missing doctype in all pages

- .github/ISSUE_TEMPLATE/bug_report.yaml
This PR add issue form for bug report.
> Add bug report issue form

- wiki/versions/1.19/markdown/1.19.md
This pull request simply adds more verbosity to the placeholder text and gives more context about the update
> Add extra verbosity to page's description

- wiki/versions/1.19/getting_started/setup/markdown/migrating_from_fabric.md
https://github.com/QuiltMC/developer-wiki/issues/49 fixing this issue, prob will be changed in the rewrite.
> Fixing Setup Guide

- draft.md
- src/lib/HtmlHead.svelte
- src/lib/types.d.ts
- src/routes/+layout.server.ts
- src/routes/+layout.svelte
- src/routes/[category]/[slug]/+page.svelte
- src/routes/[category]/[slug]/+page.ts
- svelte.config.js
- wiki/blocks/oriented-block.md
- wiki/blocks/redstone-interaction.md
- wiki/concepts/events.md
- wiki/concepts/libraries.md
- wiki/concepts/lifecycles-ticks.md
- wiki/concepts/minecraft-code-structure.md
- wiki/concepts/mixins.md
- wiki/concepts/nbt.md
- wiki/concepts/networking.md
- wiki/concepts/qsl-qfapi.md
- wiki/concepts/registries.md
- wiki/concepts/sideness.md
- wiki/data/adding-recipes.md
- wiki/data/rea.md
- wiki/data/recipe-api.md
- wiki/data/recipe-type.md
- wiki/items/armor.md
- wiki/items/tools.md
- wiki/misc/commands.md
- Adds a banner warning that the wiki is still in development
- Hides empty/draft articles from the sidebar & displays a warning if one is visited
- Fixes padding between headings
- Makes Border a lot smaller
- Adds margin to toc
---
See preview on Cloudflare Pages: https://20b1a715.developer-wiki.pages.dev/ *cough, cough, nothing to see here*
> Quick fixes for publishing

- wiki/blocks/first-block.md
QuiltBlockSettings uses .create() and not a constructor
---
See preview on Cloudflare Pages: https://preview-59.developer-wiki.pages.dev
> Update example in first-block.md

- wiki/concepts/qsl-qfapi.md
- wiki/data/resource-loader.md
- wiki/items/first-item.md
Attempts to explain:
- what APIs in general are and how to use them
- the relation between QSL, QFAPI and FAPI, and what their respective usecases are
---
See preview on Cloudflare Pages: https://2582e33c.developer-wiki.pages.dev/
> Add concepts/qsl-fapi wiki article

- wiki/introduction/get-started.md
- wiki/introduction/setting-up.md
The overall target is to make the articles clearer and less confusing to people new to modding.
- Fixes a few typos
- Improved how to use this wiki to accomodate for changes and the floating TODOs
- Restructured downloading the template mod into a heading for the zip and one for the template, to make the steps clearer.
- Added a Overview over Intellij IDEA
- Added better explanations for Making the Mod Yours
---
See preview on Cloudflare Pages: https://preview-64.developer-wiki.pages.dev
> Improve introduction category

- wiki/concepts/qsl-qfapi/fr.md
Fixes a broken link in a translated blog page that prevented building
---
See preview on Cloudflare Pages: https://preview-73.developer-wiki.pages.dev
> Quick fix so it actually builds

- wiki/items/food/en.md
Changed `FoodComponent.Bulder` to `FoodComponent.Builder`
---
See preview on Cloudflare Pages: https://preview-78.developer-wiki.pages.dev
> Fixed a typo in food/en.md

- wiki/introduction/setting-up/fr.md
- wiki/items/food/fr.md
Fixes the typo in food/fr.md that was fixed in food/en.md in #78
---
See preview on Cloudflare Pages: https://preview-82.developer-wiki.pages.dev
> Port fixes from the english version to the french version

- wiki/items/first-item/en.md
specifies where to put everything, and adds the step of creating a separate class for your items
---
See preview on Cloudflare Pages: https://preview-91.developer-wiki.pages.dev
> improve clarity of item page

- src/lib/translations/fr/application.json
- src/lib/translations/fr/wiki.json
- wiki/configuration/advanced-configuring/en.md
- wiki/configuration/advanced-configuring/fr.md
- wiki/configuration/config-screen/fr.md
- wiki/configuration/getting-started/en.md
- wiki/configuration/getting-started/fr.md
- wiki/configuration/metadata/en.md
- wiki/configuration/metadata/fr.md
- wiki/introduction/get-started/fr.md
- wiki/introduction/setting-up/fr.md
- wiki/items/armor/fr.md
---
See preview on Cloudflare Pages: https://preview-90.developer-wiki.pages.dev
> Translation of latest updates to French

- src/lib/NavbarLangDropdown.svelte
- src/lib/stores.ts
- src/lib/svelte-markdown/NoPreloadLink.svelte
- src/lib/translations/en/application.json
- src/lib/translations/en/wiki.json
- src/lib/translations/fr/application.json
- src/lib/translations/fr/wiki.json
- src/routes/+layout.svelte
- src/routes/[[locale=locale]]/[category]/[[slug]]/+page.svelte
- src/routes/[[locale=locale]]/[category]/[[slug]]/+page.ts
- In the "the main version of the wiki is the english one" info message
- In the "this wiki is not yet translated in your locale" info message
---
See preview on Cloudflare Pages: https://preview-94.developer-wiki.pages.dev
> Added links to the english version for easier navigation

- src/routes/+layout.svelte
add a bigger padding for sections, uses same value as the main website does
---
See preview on Cloudflare Pages: https://preview-101.developer-wiki.pages.dev
> increase section padding

- src/lib/HtmlHead.svelte
- src/routes/[[locale=locale]]/+page.svelte
- src/routes/[[locale=locale]]/[category]/[[article]]/+page.svelte
- wiki/introduction/getting-started/fr.md
- wiki/introduction/setting-up/fr.md
- wiki/items/first-item/fr.md
- wiki/misc/mappings/en.md
- wiki/misc/mappings/fr.md
- wiki/misc/world_types/en.md
- wiki/misc/world_types/fr.md
---
See preview on Cloudflare Pages: https://preview-105.developer-wiki.pages.dev
> translation: update french translation and translate new articles

- wiki/landing-page/en.md
---
See preview on Cloudflare Pages: https://preview-112.developer-wiki.pages.dev
> add blurb about contributing to landing page

- wiki/landing-page/en.md
---
See preview on Cloudflare Pages: https://preview-117.developer-wiki.pages.dev
> add blurb about translating the dev wiki
